EXP_NAME="KDFM_dev"
SPLIT_ID=1
SAVE_DIR=checkpoints/voc/${EXP_NAME}
IMAGENET_PRETRAIN=ImageNetPretrained/MSRA/R-101.pkl
IMAGENET_PRETRAIN_TORCH=ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth
# IMAGENET_PRETRAIN=${SAVE_DIR}/defrcn_det_r101_base${SPLIT_ID}/model_final.pth
NUM_GPUS=1
# export CUDA_VISIBLE_DEVICES=2,3

   # MODEL.PROPOSAL_GENERATOR.NAME KDRPN
cfg_MODEL="
   MODEL.META_ARCHITECTURE KDRCNN
   MODEL.ROI_HEADS.NAME KDFMRes5ROIHeads
   MODEL.ADDITION.TEACHER_TRAINING False
   MODEL.ADDITION.STUDENT_TRAINING True
   MODEL.ADDITION.DISTILL_ON True
   MODEL.ADDITION.NAME glove
   MODEL.ADDITION.INFERENCE_WITH_GT False
   MODEL.ADDITION.KD_TEMP 5
   SOLVER.IMS_PER_BATCH 8
   SOLVER.MAX_ITER 30000
   SOLVER.CHECKPOINT_PERIOD 15000
"

# cfg_MODEL="
#    MODEL.META_ARCHITECTURE KDRCNN
#    MODEL.ROI_HEADS.NAME KDFMRes5ROIHeads
#    MODEL.PROPOSAL_GENERATOR.NAME KDRPN
#    MODEL.ADDITION.TEACHER_TRAINING False
#    MODEL.ADDITION.STUDENT_TRAINING True
#    MODEL.ADDITION.DISTILL_ON False
#    MODEL.ADDITION.NAME glove
#    MODEL.ADDITION.INFERENCE_WITH_GT False
#    MODEL.ADDITION.KD_TEMP 5
#    SOLVER.IMS_PER_BATCH 8
#    SOLVER.MAX_ITER 30000
#    SOLVER.CHECKPOINT_PERIOD 15000
# "

python3 main.py --num-gpus ${NUM_GPUS} --dist-url auto --config-file configs/voc/defrcn_det_r101_base${SPLIT_ID}.yaml \
   --opts MODEL.WEIGHTS ${IMAGENET_PRETRAIN} \
   OUTPUT_DIR ${SAVE_DIR}/defrcn_det_r101_base${SPLIT_ID} ${cfg_MODEL}
exit